### ISSUE TITLE
is workarea-affirm compatible with workarea 3.5 ? 

### ISSUE THREAD

**Issue by roseliux** [workarea-commerce/workarea-affirm#6] opened 2020-07-01 16:31 UTC
I am having the following errors when trying to install the gem on my project with workarea 3.5.14

```
Bundler could not find compatible versions for gem "haml":
  In snapshot (Gemfile.lock):
    haml (= 5.0.4)

  In Gemfile:
    weblinc-affirm was resolved to 0.1.0, which depends on
      weblinc (< 0.13) was resolved to 0.4.0.beta3, which depends on
weblinc-store_front (= 0.4.0.beta3) was resolved to 0.4.0.beta3, which depends
on
          haml (~> 4.0.5)

    workarea-ci was resolved to 4.0.0, which depends on
      workarea-core (>= 3.4.x) was resolved to 3.5.14, which depends on
        haml (~> 5.0.1)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
```

Any help is welcome 🙏

**Comment by bencrouse** [comment] 2020-07-01 18:06
Hi, this looks like a mixup in the gems installed maybe? I'm not sure why it's asking for `weblinc < 0.13`, you can see this gems dependency on base here: https://github.com/workarea-commerce/workarea-affirm/blob/master/workarea-affirm.gemspec#L28

It's definitely v3.5 compatible, so I'm closing since this isn't an issue with this gem. If you're looking for support try the usual places like our developer community Slack channel or Discourse forum.

**Closed as completed by bencrouse** 2020-07-01 18:06 UTC

**Comment by roseliux** [comment] 2020-07-01 18:17
Ok thanks for the guideline I will do that.

**Comment by roseliux** [comment] 2020-07-01 19:20
@bencrouse  we might open this back again I don't found the workarea-affirm gem when I have the following code on my Gemfile

```
source 'https://gems.weblinc.com' do
    gem 'workarea-affirm'
end
```

receiving the following error:
```
Could not find gem 'workarea-affirm' in rubygems repository https://gems.weblinc.com/ or
installed locally.
```

And updating this guide will be helpful https://plugins.workarea.com/plugins/affirm since is pointing to the old
`  gem 'weblinc-affirm'`

Thanks for all the help, waiting on you answer 😄

**Comment by bencrouse** [comment] 2020-07-02 12:10
This gem isn't on `https://gems.weblinc.com`, it's on rubygems, so you'll want to remove that source block from around it.

The problem is with the Gemfile, there isn't a problem with the gem, so I'm going to leave the issue closed.

**Comment by roseliux** [comment] 2020-07-02 17:14
try to install it with `gem 'workarea-affirm', source: 'https://rubygems.org'` and got
```
Could not find gem 'workarea-affirm' in rubygems repository https://rubygems.org/ or
installed locally.
The source does not contain any versions of 'workarea-affirm'
```
